apiVersion: policies.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: policy
spec:
  evaluation:
    mode: Envoy
  variables:
    - name: mcpBody
      expression: json(object.attributes.request.http.body)
    - name: jwks
      expression: jwks.Fetch("http://keycloak.keycloak.svc.cluster.local/realms/master/protocol/openid-connect/certs")
    - name: jwtString
      expression: object.attributes.request.http.headers.authorization.split(" ")[1]
    - name: decodedJwt
      expression: jwt.Decode(variables.jwtString, variables.jwks)
    - name: tenant
      expression: variables.decodedJwt.Claims["tenant"]
    # - name: namespaceExists
    #   expression: resource.List("", "namespaces", "").items.exists(i, i.metadata.name == string(variables.mcpBody.params.arguments.namespace))
    - name: namespaceExists
      expression: dyn(resource.List("v1", "namespaces", "").items).exists(i, i.metadata.name == variables.mcpBody.params.arguments.namespace)
  validations:
  - expression: |
      variables.namespaceExists ? envoy.Allowed().Response() : envoy.Denied(403).Response()